// Enforce the selective YouTube allowlist and strip the "rabbit hole" surfaces.
// Runs at document_start in ALL frames on youtube.com + youtube-nocookie.com.
// YouTube is a single-page app, so we re-evaluate on every in-app navigation
// (yt-navigate-finish) as well as initial load.
//
// SOURCE OF THE ALLOWLIST: chrome.storage.managed, delivered LIVE by the managed
// policy /etc/opt/chrome/policies/managed/parental.json (regenerated by
// scripts/regenerate.sh, via the `allow-youtube` helper). Changing the allowlist
// needs NO extension repack — only a policy refresh, which this script also
// picks up on the fly via chrome.storage.onChanged. The baked-in config.js is
// only a fail-safe fallback (empty => block everything) used when managed policy
// is unavailable.
//
// HOW A VIDEO IS JUDGED (v1.1.0): the background service worker is the single
// verdict authority. It resolves the video's OWNER (channel id / @handle) via
// YouTube's oEmbed metadata endpoint — never by scraping this page's DOM — and
// compares it to the allowlist. Watch pages and embeds use the SAME verdict, so
// an approved-channel video plays anywhere (watch page, channel click-through,
// embeds on allowlisted sites) and a non-approved video plays nowhere. The old
// DOM owner-link check survives only as a last-resort fallback when the
// metadata lookup is unreachable, and it now treats a missing/empty owner href
// as "not loaded yet" instead of "wrong channel" (the bug that blocked
// approved-channel videos opened from their channel page).
//
// Policy:
//   /watch?v=ID            -> allowed if ID is whitelisted OR the video's owner
//                             matches a whitelisted channel/handle (verdict).
//   /embed|/v|/e/ID        -> same verdict (any frame, incl. nocookie).
//   /channel/UCxxxx, /@h   -> allowed if that channel/handle is whitelisted.
//   everything else        -> blocked (home, results, shorts, feed, trending).
// Restricted Mode (content rating) is forced underneath this by DNS.

(function () {
  // Fail-safe fallback baked into the extension (empty => block everything).
  const FALLBACK = globalThis.PARENTAL_CONFIG || { youtubeChannels: [], youtubeVideos: [], youtubeHandles: [] };

  let channels = new Set();
  let videos = new Set();
  let handles = new Set();

  function applyConfig(cfg) {
    channels = new Set(cfg.youtubeChannels || []);
    videos = new Set(cfg.youtubeVideos || []);
    handles = new Set((cfg.youtubeHandles || []).map((h) => String(h).toLowerCase()));
  }
  applyConfig(FALLBACK); // safe default until managed policy resolves

  // Always hide recommendations / shorts / comments / autoplay surfaces.
  const css = `
    ytd-reel-shelf-renderer, ytd-rich-shelf-renderer,
    #related, ytd-watch-next-secondary-results-renderer,
    ytd-comments, #comments,
    ytd-guide-section-renderer a[title="Shorts"],
    ytd-mini-guide-entry-renderer[aria-label="Shorts"],
    a[title="Shorts"], ytd-reel-shelf-renderer { display: none !important; }
    #movie_player .ytp-autonav-toggle-button-container { display: none !important; }
  `;
  const style = document.createElement("style");
  style.textContent = css;
  (document.head || document.documentElement).appendChild(style);

  function report(reason) {
    try { chrome.runtime.sendMessage({ type: "blocked", url: location.href, reason }); } catch (_) {}
  }

  function block(reason) {
    report(reason);
    try { window.stop(); } catch (_) {}
    document.documentElement.innerHTML = `
      <html><head><title>Blocked</title></head>
      <body style="font-family:system-ui;background:#111;color:#eee;display:flex;
        align-items:center;justify-content:center;height:100vh;margin:0;text-align:center">
        <div>
          <h1>This video isn't on your allowed list</h1>
          <p>Ask a parent to add it if you need it.</p>
          <p style="opacity:.5;font-size:.8em">${reason}</p>
        </div>
      </body></html>`;
  }

  // Ask the background worker for the allow/deny verdict on a video id.
  // Resolves {allowed, verified, why}; never rejects. If the worker can't be
  // reached at all, the answer is "unverified" and the caller fails closed.
  function askVerdict(id) {
    return new Promise((resolve) => {
      let done = false;
      const finish = (v) => {
        if (done) return;
        done = true;
        resolve(v && typeof v.allowed === "boolean" ? v : { allowed: false, verified: false, why: "no answer" });
      };
      const timer = setTimeout(() => finish({ allowed: false, verified: false, why: "verdict timeout" }), 8000);
      try {
        chrome.runtime.sendMessage({ type: "ytVerdict", id }, (resp) => {
          clearTimeout(timer);
          if (chrome.runtime.lastError) finish({ allowed: false, verified: false, why: "no background" });
          else finish(resp);
        });
      } catch (_) {
        clearTimeout(timer);
        finish({ allowed: false, verified: false, why: "no background" });
      }
    });
  }

  // Guard against SPA races: only act on a verdict if the user is still on the
  // page that asked for it.
  function here() { return location.pathname + location.search; }
  function stillHere(token) { return token === here(); }

  // --- last-resort DOM fallback (only when the metadata lookup failed) ------
  // Reads the channel-owner link under the video. Returns:
  //   true  -> owner parsed AND allowlisted
  //   false -> owner parsed and NOT allowlisted (definitive mismatch)
  //   null  -> owner not available/parseable yet (skeleton DOM, empty href)
  function ownerMatches() {
    const a =
      document.querySelector("ytd-video-owner-renderer a") ||
      document.querySelector("#owner a") ||
      document.querySelector("a.ytd-video-owner-renderer");
    if (!a) return null;
    const href = a.getAttribute("href") || "";
    const ch = href.match(/\/channel\/(UC[\w-]+)/);
    if (ch) return channels.has(ch[1]);
    const h = href.match(/\/(@[\w.\-]+)/);
    if (h) return handles.has(h[1].toLowerCase());
    return null; // empty or unparseable href => NOT a mismatch, just not loaded
  }
  function domFallback(token) {
    const decide = () => {
      if (!stillHere(token)) return true; // navigated away; stop
      const m = ownerMatches();
      if (m === true) return true;
      if (m === false) { block("video's channel not allowed"); return true; }
      return false; // unknown yet — keep observing
    };
    if (decide()) return;
    const obs = new MutationObserver(() => { if (decide()) obs.disconnect(); });
    obs.observe(document.documentElement, { childList: true, subtree: true });
    setTimeout(() => {
      obs.disconnect();
      if (stillHere(token) && ownerMatches() !== true) block("could not verify channel");
    }, 8000);
  }

  // Are we the top-level page, or an embedded frame (e.g. a YouTube player
  // iframed into another allowlisted site)?
  const isTop = (function () { try { return window.top === window.self; } catch (_) { return false; } })();

  function evaluate() {
    const path = location.pathname;
    const params = new URLSearchParams(location.search);
    const token = here();

    // Embedded player paths — how other sites play YouTube without
    // youtube.com/watch: /embed/ID , /v/ID , /e/ID (also on nocookie).
    // Same verdict as a watch page: allowed-channel videos play, others don't.
    const em = path.match(/^\/(?:embed|v|e)\/([\w-]{6,})/);
    if (em) {
      if (videos.has(em[1])) return; // explicit allow, no roundtrip
      askVerdict(em[1]).then((v) => {
        if (v.allowed || !stillHere(token)) return;
        block(v.verified ? `embedded video not allowed (${v.why})`
                         : `embedded video could not be verified (${v.why})`);
      });
      return;
    }

    // A non-embed sub-frame (e.g. a helper iframe inside an allowed watch
    // page): leave it alone so we don't blank legitimate frames. Only the top
    // frame is subject to the page policy below.
    if (!isTop) return;

    if (path === "/watch") {
      const vid = params.get("v");
      if (!vid) { block("watch page without a video id"); return; }
      if (videos.has(vid)) return; // explicit allow, no roundtrip
      askVerdict(vid).then((v) => {
        if (v.allowed || !stillHere(token)) return;
        if (v.verified) { block(`video's channel not allowed (${v.why})`); return; }
        domFallback(token); // metadata unreachable — try the page DOM, else block
      });
      return;
    }

    const chMatch = path.match(/^\/channel\/(UC[\w-]+)/);
    if (chMatch) { if (!channels.has(chMatch[1])) block("channel not allowed"); return; }

    const hMatch = path.match(/^\/(@[\w.\-]+)/);
    if (hMatch) { if (!handles.has(hMatch[1].toLowerCase())) block("channel not allowed"); return; }

    // Home, search results, shorts, feeds, trending, etc.
    block("only specific channels/videos are allowed");
  }

  // --- Live allowlist from managed policy -----------------------------------
  function hasManaged(items) {
    return !!items && (
      Array.isArray(items.youtubeChannels) ||
      Array.isArray(items.youtubeVideos) ||
      Array.isArray(items.youtubeHandles)
    );
  }
  function loadManaged() {
    return new Promise((resolve) => {
      try {
        chrome.storage.managed.get(
          ["youtubeChannels", "youtubeVideos", "youtubeHandles", "restrictMode"],
          (items) => {
            if (!chrome.runtime.lastError && hasManaged(items)) applyConfig(items);
            resolve();
          }
        );
      } catch (_) { resolve(); }
    });
  }

  // If the parent edits the allowlist while a tab is open and Chrome refreshes
  // its policy, re-apply and re-evaluate immediately — no reload needed.
  try {
    chrome.storage.onChanged.addListener((changes, area) => {
      if (area !== "managed") return;
      loadManaged().then(evaluate);
    });
  } catch (_) {}

  const ready = loadManaged();
  function run() { ready.then(evaluate); }

  // Initial + SPA navigations.
  window.addEventListener("yt-navigate-finish", run, true);
  document.addEventListener("DOMContentLoaded", run, true);
  run();
})();
