// Enforce the selective YouTube allowlist and strip the "rabbit hole" surfaces.
// Runs at document_start. YouTube is a single-page app, so we re-evaluate on
// every in-app navigation (yt-navigate-finish) as well as initial load.
//
// SOURCE OF THE ALLOWLIST: chrome.storage.managed, delivered LIVE by the managed
// policy /etc/opt/chrome/policies/managed/parental.json (regenerated by
// scripts/regenerate.sh, via the `allow-youtube` helper). Changing the allowlist
// needs NO extension repack — only a policy refresh, which this script also
// picks up on the fly via chrome.storage.onChanged. The baked-in config.js is
// only a fail-safe fallback (empty => block everything) used when managed policy
// is unavailable.
//
// Policy:
//   /watch?v=ID        -> allowed if ID is whitelisted, OR the video's channel
//                         (owner link) matches a whitelisted channel/handle.
//   /channel/UCxxxx    -> allowed if that channel id is whitelisted.
//   /@handle           -> allowed if that handle is whitelisted.
//   everything else    -> blocked (home, results, shorts, feed, trending...).
// Restricted Mode (content rating) is forced underneath this by DNS.

(function () {
  // Fail-safe fallback baked into the extension (empty => block everything).
  const FALLBACK = globalThis.PARENTAL_CONFIG || { youtubeChannels: [], youtubeVideos: [], youtubeHandles: [] };

  let channels = new Set();
  let videos = new Set();
  let handles = new Set();

  function applyConfig(cfg) {
    channels = new Set(cfg.youtubeChannels || []);
    videos = new Set(cfg.youtubeVideos || []);
    handles = new Set((cfg.youtubeHandles || []).map((h) => String(h).toLowerCase()));
  }
  applyConfig(FALLBACK); // safe default until managed policy resolves

  // Always hide recommendations / shorts / comments / autoplay surfaces.
  const css = `
    ytd-reel-shelf-renderer, ytd-rich-shelf-renderer,
    #related, ytd-watch-next-secondary-results-renderer,
    ytd-comments, #comments,
    ytd-guide-section-renderer a[title="Shorts"],
    ytd-mini-guide-entry-renderer[aria-label="Shorts"],
    a[title="Shorts"], ytd-reel-shelf-renderer { display: none !important; }
    #movie_player .ytp-autonav-toggle-button-container { display: none !important; }
  `;
  const style = document.createElement("style");
  style.textContent = css;
  (document.head || document.documentElement).appendChild(style);

  function report(reason) {
    try { chrome.runtime.sendMessage({ type: "blocked", url: location.href, reason }); } catch (_) {}
  }

  function block(reason) {
    report(reason);
    try { window.stop(); } catch (_) {}
    document.documentElement.innerHTML = `
      <html><head><title>Blocked</title></head>
      <body style="font-family:system-ui;background:#111;color:#eee;display:flex;
        align-items:center;justify-content:center;height:100vh;margin:0;text-align:center">
        <div>
          <h1>This video isn't on your allowed list</h1>
          <p>Ask a parent to add it if you need it.</p>
          <p style="opacity:.5;font-size:.8em">${reason}</p>
        </div>
      </body></html>`;
  }

  function ownerMatches() {
    // The channel owner link appears under the video; read its href.
    const a =
      document.querySelector("ytd-video-owner-renderer a") ||
      document.querySelector("#owner a") ||
      document.querySelector('a.ytd-video-owner-renderer');
    if (!a) return null; // not loaded yet
    const href = a.getAttribute("href") || "";
    const ch = href.match(/\/channel\/(UC[\w-]+)/);
    if (ch && channels.has(ch[1])) return true;
    const h = href.match(/\/(@[\w.\-]+)/);
    if (h && handles.has(h[1].toLowerCase())) return true;
    return false;
  }

  // Are we the top-level page, or an embedded frame (e.g. a YouTube player
  // iframed into a Google search result or any other site)?
  const isTop = (function () { try { return window.top === window.self; } catch (_) { return false; } })();

  function evaluate() {
    const path = location.pathname;
    const params = new URLSearchParams(location.search);

    // Embedded player paths — these are how OTHER sites (Google search inline
    // preview, blogs, etc.) play YouTube without hitting youtube.com/watch:
    //   /embed/ID , /v/ID , /e/ID   (on youtube.com AND youtube-nocookie.com)
    // Only an EXPLICITLY allowlisted video id may play this way; everything
    // else is blocked. This closes the iframe-embed bypass.
    const em = path.match(/^\/(?:embed|v|e)\/([\w-]{6,})/);
    if (em) {
      if (videos.has(em[1])) return;
      block("embedded video not allowed");
      return;
    }

    // A non-embed sub-frame (e.g. a helper iframe inside an allowed watch page):
    // leave it alone so we don't blank legitimate frames. Only the top frame is
    // subject to the home/search/channel policy below.
    if (!isTop) return;

    if (path === "/watch") {
      const v = params.get("v");
      if (v && videos.has(v)) return; // explicit video allow
      // Need the channel; it loads after the player. Observe until known.
      const decide = () => {
        const m = ownerMatches();
        if (m === true) return true;
        if (m === false) { block("video's channel not allowed"); return true; }
        return false; // unknown yet
      };
      if (decide()) return;
      const obs = new MutationObserver(() => { if (decide()) obs.disconnect(); });
      obs.observe(document.documentElement, { childList: true, subtree: true });
      // Safety timeout: if owner never resolves, block.
      setTimeout(() => { if (ownerMatches() !== true) { obs.disconnect(); block("could not verify channel"); } }, 6000);
      return;
    }

    const chMatch = path.match(/^\/channel\/(UC[\w-]+)/);
    if (chMatch) { if (!channels.has(chMatch[1])) block("channel not allowed"); return; }

    const hMatch = path.match(/^\/(@[\w.\-]+)/);
    if (hMatch) { if (!handles.has(hMatch[1].toLowerCase())) block("channel not allowed"); return; }

    // Home, search results, shorts, feeds, trending, etc.
    block("only specific channels/videos are allowed");
  }

  // --- Live allowlist from managed policy -----------------------------------
  function hasManaged(items) {
    return !!items && (
      Array.isArray(items.youtubeChannels) ||
      Array.isArray(items.youtubeVideos) ||
      Array.isArray(items.youtubeHandles)
    );
  }
  function loadManaged() {
    return new Promise((resolve) => {
      try {
        chrome.storage.managed.get(
          ["youtubeChannels", "youtubeVideos", "youtubeHandles", "restrictMode"],
          (items) => {
            if (!chrome.runtime.lastError && hasManaged(items)) applyConfig(items);
            resolve();
          }
        );
      } catch (_) { resolve(); }
    });
  }

  // If the parent edits the allowlist while a tab is open and Chrome refreshes
  // its policy, re-apply and re-evaluate immediately — no reload needed.
  try {
    chrome.storage.onChanged.addListener((changes, area) => {
      if (area !== "managed") return;
      loadManaged().then(evaluate);
    });
  } catch (_) {}

  const ready = loadManaged();
  function run() { ready.then(evaluate); }

  // Initial + SPA navigations.
  window.addEventListener("yt-navigate-finish", run, true);
  document.addEventListener("DOMContentLoaded", run, true);
  run();
})();
